# Generated by Django 2.0.3 on 2018-07-08 10:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedianVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the median voting', max_length=150)),
                ('value', models.PositiveIntegerField(help_text='Value for this voting (for example 2000 (cent))')),
                ('percent_required', models.DecimalField(decimal_places=1, default=Decimal('50.0'), help_text='Percent of votes required, for example 50 (half of all votes) or 75 (three-quarters)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the period, for example "Summer Term 2018"', max_length=150, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Time when the category was created')),
                ('start', models.DateField(blank=True, help_text='Start of the period (for example start of term)', null=True)),
                ('end', models.DateField(blank=True, help_text='End ofthe period (for example end of term)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the voter / group', max_length=150)),
                ('weight', models.PositiveIntegerField(help_text='Weight of the votes, i.e. how many votes the voter actually casts')),
            ],
        ),
        migrations.CreateModel(
            name='VotersRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Time when the revision was created')),
                ('note', models.TextField(help_text='Optional note for this revision')),
                ('period', models.ForeignKey(help_text='Period this revision is used in', on_delete=django.db.models.deletion.CASCADE, to='votings.Period')),
            ],
        ),
        migrations.CreateModel(
            name='VotingCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the collection (for example "StuRa-Sitzung vom XX.XX.XXXX")', max_length=150)),
                ('time', models.DateTimeField(help_text='Time the votings take place')),
                ('revision', models.ForeignKey(help_text='Group of voters for this voting', on_delete=django.db.models.deletion.CASCADE, to='votings.VotersRevision')),
            ],
        ),
        migrations.CreateModel(
            name='VotingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the group, for example "Financial Votes"', max_length=150)),
                ('collection', models.ForeignKey(help_text='Collection this group belongs to', on_delete=django.db.models.deletion.CASCADE, to='votings.VotingCollection')),
            ],
        ),
        migrations.AddField(
            model_name='voter',
            name='revision',
            field=models.ForeignKey(help_text='Revision this user is used in', on_delete=django.db.models.deletion.CASCADE, to='votings.VotersRevision'),
        ),
        migrations.AddField(
            model_name='medianvoting',
            name='group',
            field=models.ForeignKey(help_text='Group this voting belongs to', on_delete=django.db.models.deletion.CASCADE, to='votings.VotingGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='votinggroup',
            unique_together={('name', 'collection')},
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('revision', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='medianvoting',
            unique_together={('name', 'group')},
        ),
    ]
