# Generated by Django 2.0.3 on 2018-08-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0002_auto_20180708_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='medianvoting',
            name='count_all_votes',
            field=models.BooleanField(default=False, help_text='Set to true if all voters should be considerd, even those who did not cast a vote. Thes voters will be treated as if they voted for 0€'),
        ),
        migrations.AddField(
            model_name='medianvoting',
            name='currency',
            field=models.CharField(blank=True, help_text='Currency of the vote, for example "$" or "€". For example value=100 and currency=€ means 1,00€.', max_length=10),
        ),
        migrations.AddField(
            model_name='schulzevoting',
            name='count_all_votes',
            field=models.BooleanField(default=False, help_text='Set to true if all voters should be considerd, even those who did not cast a vote. Thes voters will be treated as if they voted for no (which is considered to be the last option)'),
        ),
        migrations.AlterField(
            model_name='medianvoting',
            name='value',
            field=models.PositiveIntegerField(help_text='Value for this voting (for example 2000 (cent). Always meassured in cents, pence etc.)'),
        ),
    ]
