# Generated by Django 2.0.3 on 2018-08-15 03:26

from django.db import migrations, models
import votings.utils


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0004_auto_20180815_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='schulzeoption',
            name='option_num',
            field=models.PositiveIntegerField(default=0, help_text='Optionsnummer innerhalb der Schulze Abstimmung'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votingcollection',
            name='name',
            field=models.CharField(default=votings.utils.get_next_session_name_stura, help_text='Name of the collection (for example "StuRa-Sitzung vom XX.XX.XXXX")', max_length=150),
        ),
        migrations.AlterField(
            model_name='votingcollection',
            name='time',
            field=models.DateTimeField(default=votings.utils.get_next_session_stura, help_text='Time the votings take place'),
        ),
    ]
