# Generated by Django 2.0.3 on 2018-08-15 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0005_auto_20180815_0526'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medianvoting',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='schulzevoting',
            unique_together=set(),
        ),
    ]
