# Generated by Django 2.1.7 on 2019-03-27 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0006_auto_20180815_0536'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schulzeoption',
            unique_together={('option', 'voting'), ('voting', 'option_num')},
        ),
    ]
