# Generated by Django 2.1.7 on 2019-03-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0007_auto_20190327_0202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votinggroup',
            unique_together={('group_num', 'collection'), ('name', 'collection')},
        ),
    ]
