# Generated by Django 2.1.7 on 2019-04-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0008_auto_20190327_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medianvoting',
            name='percent_required',
        ),
        migrations.RemoveField(
            model_name='schulzevoting',
            name='percent_required',
        ),
        migrations.AddField(
            model_name='medianvoting',
            name='majority',
            field=models.CharField(choices=[('50', '50%'), ('2/3', '2/3 majority')], default='50', help_text='Required majority for voting', max_length=10),
        ),
        migrations.AddField(
            model_name='schulzevoting',
            name='majority',
            field=models.CharField(choices=[('50', '50%'), ('2/3', '2/3 majority')], default='50', help_text='Required majority for voting', max_length=10),
        ),
    ]
