# Generated by Django 2.1.7 on 2019-04-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0009_auto_20190402_0509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medianvoting',
            old_name='count_all_votes',
            new_name='absolute_majority',
        ),
        migrations.RenameField(
            model_name='schulzevoting',
            old_name='count_all_votes',
            new_name='absolute_majority',
        ),
    ]
