# Generated by Django 2.2 on 2019-04-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0010_auto_20190402_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medianvoting',
            name='currency',
            field=models.CharField(blank=True, default='€', help_text='Currency of the vote, for example "$" or "€". For example value=100 and currency=€ means 1,00€.', max_length=10),
        ),
    ]
