# Generated by Django 2.2 on 2019-04-18 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import votings.utils


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0012_auto_20190412_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medianvote',
            name='value',
            field=models.PositiveIntegerField(help_text='Value the voter voted for'),
        ),
        migrations.AlterField(
            model_name='medianvote',
            name='voting',
            field=models.ForeignKey(help_text='The poll in question', on_delete=django.db.models.deletion.CASCADE, to='votings.MedianVoting'),
        ),
        migrations.AlterField(
            model_name='medianvoting',
            name='name',
            field=models.CharField(help_text='Name of the poll', max_length=150),
        ),
        migrations.AlterField(
            model_name='medianvoting',
            name='voting_num',
            field=models.PositiveIntegerField(help_text='Order position inside the group'),
        ),
        migrations.AlterField(
            model_name='period',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time of creation'),
        ),
        migrations.AlterField(
            model_name='period',
            name='end',
            field=models.DateField(blank=True, default=votings.utils.get_semester_end, help_text='End date of the period', null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(default=votings.utils.get_semester_name, help_text='Name of the Period, e.g. "Summer Term 2019"', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='start',
            field=models.DateField(blank=True, default=votings.utils.get_semester_start, help_text='Start date of the period', null=True),
        ),
        migrations.AlterField(
            model_name='schulzeoption',
            name='option_num',
            field=models.PositiveIntegerField(help_text='Order position inside the poll'),
        ),
        migrations.AlterField(
            model_name='schulzeoption',
            name='voting',
            field=models.ForeignKey(help_text='Poll this option belongs to', on_delete=django.db.models.deletion.CASCADE, to='votings.SchulzeVoting'),
        ),
        migrations.AlterField(
            model_name='schulzevoting',
            name='name',
            field=models.CharField(help_text='Name of the poll', max_length=150),
        ),
        migrations.AlterField(
            model_name='schulzevoting',
            name='voting_num',
            field=models.PositiveIntegerField(help_text='Order position inside the group'),
        ),
        migrations.AlterField(
            model_name='votersrevision',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time of creation'),
        ),
        migrations.AlterField(
            model_name='votersrevision',
            name='note',
            field=models.TextField(blank=True, help_text='Optional note'),
        ),
        migrations.AlterField(
            model_name='votersrevision',
            name='period',
            field=models.ForeignKey(help_text='Period this revision belongs to', on_delete=django.db.models.deletion.CASCADE, to='votings.Period'),
        ),
        migrations.AlterField(
            model_name='votingcollection',
            name='name',
            field=models.CharField(default=votings.utils.get_next_session_name_stura, help_text='Name of the collection (e.g. "Meeting on XXX")', max_length=150),
        ),
        migrations.AlterField(
            model_name='votingcollection',
            name='revision',
            field=models.ForeignKey(help_text='Group of voters for this session', on_delete=django.db.models.deletion.CASCADE, to='votings.VotersRevision'),
        ),
        migrations.AlterField(
            model_name='votingcollection',
            name='time',
            field=models.DateTimeField(default=votings.utils.get_next_session_stura, help_text='Time the session takes place'),
        ),
        migrations.AlterField(
            model_name='votinggroup',
            name='group_num',
            field=models.PositiveIntegerField(help_text='Order of the group in the session'),
        ),
    ]
