# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 15:57
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percent_required', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Prozent die nötig sind, damit die Abstimmung als angenommen gilt', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Prozent')),
                ('all_votes', models.BooleanField(default=False, help_text='Wenn aktiviert werden ALLE Stimmen gezählt, auch jene die nicht mit abgestimmt haben!', verbose_name='Alle Stimmen?')),
            ],
        ),
        migrations.CreateModel(
            name='VotingDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Datum an dem die Abstimmungen durchgeführt werden.', verbose_name='Datum')),
            ],
        ),
        migrations.CreateModel(
            name='VotingTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellungszeitpunkt')),
                ('name', models.CharField(help_text='Name der Abstimmungsperiode', max_length=40, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='VotingWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name der abstimmenden Gruppe', max_length=75, verbose_name='Name')),
                ('weight', models.PositiveSmallIntegerField(help_text='Die Abstimmungsgewichtung der Gruppe', verbose_name='Gewichtung')),
            ],
        ),
        migrations.CreateModel(
            name='VotingWeightGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.ForeignKey(help_text='Abstimmungszeitraum dem diese Gewichtung zugeordnet wird', on_delete=django.db.models.deletion.CASCADE, to='votes.VotingTerm', verbose_name='Abstimmungszeitraum')),
            ],
        ),
        migrations.AddField(
            model_name='votingweight',
            name='group',
            field=models.ForeignKey(help_text='Gruppe zu der diese Eintragung gehört', on_delete=django.db.models.deletion.CASCADE, to='votes.VotingWeightGroup', verbose_name='Gruppe'),
        ),
        migrations.AddField(
            model_name='votingday',
            name='weights',
            field=models.ForeignKey(help_text='Gewichtungsgruppe welche zur Auszählung verwendet wird', on_delete=django.db.models.deletion.CASCADE, to='votes.VotingWeightGroup', verbose_name='Gewichtungsgruppe'),
        ),
        migrations.AlterUniqueTogether(
            name='votingweight',
            unique_together=set([('group', 'name')]),
        ),
    ]
